name: CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    defaults:
      run:
        shell: bash
        working-directory: ./my-react-app
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install dependencies
        run: npm install    
 #     - name: Test
 #       run: npm test
 #       env:
 #         CI: true
      - name: Generate build
        run: npm run build
      # Share artifact inside workflow
      - name: Share artifact inside workflow
        uses: actions/upload-artifact@v1
        with:
          name: frontend-artifact
          path: my-react-app/build
  
  deploy:
    # The type of runner that the job will run on
    needs: build
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      contents: read
      id-token: write

    steps:
    - name: Clone repository
      uses: actions/checkout@v2
    - name: Get artifact
      uses: actions/download-artifact@v1
      with:
        name: frontend-artifact
        path: ${{ github.workspace }}/my-react-app/
      
    - id: auth
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}      
        
    - name: Deploy to App Engine
      id: deploy
      uses: google-github-actions/deploy-appengine@v0
      with:
        working_directory: ${{ github.workspace }}/my-react-app/
        deliverables: app.yml
        promote: false
        version: v1
        
    - id: test
      run: curl "${{ steps.deploy.outputs.url }}"
